version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_dev
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  redis:
    image: redis
    container_name: redis_dev
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data

  node-server:
    build:
      context: .
    container_name: node-server
    ports:
      - '${PORT}:8000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
      - postgres
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DATABASE_URL: ${DATABASE_URL_POSTGRES}
      REDIS_URL: ${REDIS_URL_REDIS}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  redis-data:
  postgres-data:
