version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_dev
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  redis:
    image: redis
    container_name: redis_dev
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
    environment:
      REDIS_HOST: ${REDIS_HOST}

  node-server:
    image: tuplawee7/node-server:latest
    container_name: node-server
    ports:
      - '${PORT}:8080'
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - postgres
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
    command: >
      sh -c "npx prisma migrate dev --name init &&
             npx prisma generate &&
             npm run dev"

volumes:
  redis-data:
  postgres-data:
